const CHANGE_TAB = 'CHANGE_TAB';
const CREATE_NEW_TAB = 'CREATE_NEW_TAB';
const SHOW_LOADER = 'SHOW_LOADER';
const HIDE_LOADER = 'HIDE_LOADER';
const SET_RESPONSE_VIEW = 'SET_RESPONSE_VIEW';
const OPEN_AlERT = 'OPEN_AlERT';
const CLOSE_ALERT = 'CLOSE_ALERT';

export {
  CHANGE_TAB,
  CREATE_NEW_TAB,
  SHOW_LOADER,
  HIDE_LOADER,
  SET_RESPONSE_VIEW,
  OPEN_AlERT,
  CLOSE_ALERT,
};
