const CHANGE_TAB = 'CHANGE_TAB';
const CREATE_NEW_TAB = 'CREATE_NEW_TAB';
const SET_LOADER = 'SET_LOADER';
const SET_RESPONSE_VIEW = 'SET_RESPONSE_VIEW';

export { CHANGE_TAB, CREATE_NEW_TAB, SET_LOADER, SET_RESPONSE_VIEW };
